import type { Metadata } from "next";
import {NuqsAdapter} from "nuqs/adapters/next"
import { TRPCReactProvider } from "@/trpc/client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { createTRPCContext } from "@trpc/tanstack-react-query";
import { redirect } from "next/navigation";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <>
    <NuqsAdapter>
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className}  antialiased`}
        >
          <Toaster/>
          {children}
        </body>
      </html>
    </TRPCReactProvider>
    </NuqsAdapter></>
  );
}
